---
# mail_after_reboot/tasks/set_facts.yml

- name: 'Set variable to use s-nail on Debian and derivatives'
  ansible.builtin.set_fact:
    mail_executable: '/usr/bin/s-nail'
    mail_package_name: 's-nail'
  when:
    - 'ansible_os_family == "Debian"'

- name: 'Set variable to use mailx on RHEL7/CentOS7'
  ansible.builtin.set_fact:
    mail_package_name: 'mailx'
  when:
    - 'ansible_os_family == "RedHat"'
    - 'ansible_distribution_major_version | int == 7'

- name: 'Set variable to use mailx on RHEL8/CentOS8/RockyLinux8/AlmaLinux8'
  ansible.builtin.set_fact:
    mail_package_name: 'mailx'
  when:
    - '
      ansible_os_family == "RedHat"
      or ansible_os_family == "Rocky"
      '
    - 'ansible_distribution_major_version | int == 8'

- name: 'Set variable to use mailx on SUSE/openSUSE'
  ansible.builtin.set_fact:
    mail_package_name: 'mailx'
  when:
    - 'ansible_os_family == "Suse" or ansible_os_family == "openSUSE MicroOS"'
